kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bench-dd-pv-claim
spec:
  #storageClassName: openebs-device-nvme-xfs
  #storageClassName: openebs-hostpath-nvme-xfs
  #storageClassName: openebs-local-nvme-sparse
  #storageClassName: openebs-nvme-zpool-xfs
  #storageClassName: openebs-nvme-zpool-zfs
  storageClassName: openebs-hostpath
  #storageClassName: openebs-rawfile
  #storageClassName: openebs-rawfile-xfs
  #storageClassName: openebs-rawfile-ext4
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: bench-dd
spec:
  template:
    spec:
      containers:
      - name: bench-dd
        image: kiranmova/alpine-fio:latest
        imagePullPolicy: Always
        command:
          - sh
          - -c
          #- '/docker-entrypoint.sh ext-fio'
          #- '/docker-entrypoint.sh fio'
          - "date; time dd if=/dev/zero of=/data/zeros.dat bs=4024 count=500000 && sync ; date"
        env:
          - name: FBENCH_MOUNTPOINT
            value: /data
          #- name: FBENCH_QUICK
          #  value: "yes"
          # - name: FIO_SIZE
          #   value: 1G
          # - name: FIO_OFFSET_INCREMENT
          #   value: 256M
          # - name: FIO_DIRECT
          #   value: "0"
        volumeMounts:
        - name: bench-pv
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: bench-pv
        persistentVolumeClaim:
          claimName: bench-dd-pv-claim
  backoffLimit: 4
