apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-rawfile-ext4
provisioner: rawfile.csi.openebs.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
