apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-device-local
allowVolumeExpansion: true
parameters:
  devname: "test-device"
provisioner: device.csi.openebs.io
volumeBindingMode: WaitForFirstConsumer
