apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
 name: cstor-disk-pool
 namespace: openebs
spec:
 pools:
   - nodeSelector:
       kubernetes.io/hostname: "gke-kmova-helm-default-pool-2e22e2c6-vr2j"
     dataRaidGroups:
       - blockDevices:
           # /dev/sdc1   375 GiB
           - blockDeviceName: "blockdevice-9de2af5f4fad35d8530691acb6f3a5a3"
     poolConfig:
       dataRaidGroupType: "stripe"
 
   - nodeSelector:
       kubernetes.io/hostname: "gke-kmova-helm-default-pool-2e22e2c6-6q81"
     dataRaidGroups:
       - blockDevices:
           # /dev/sdc1   375 GiB
           - blockDeviceName: "blockdevice-3a3d6cf985027842e3a452eae39748c6"
     poolConfig:
       dataRaidGroupType: "stripe"
 
   - nodeSelector:
       kubernetes.io/hostname: "gke-kmova-helm-default-pool-2e22e2c6-6gz2"
     dataRaidGroups:
       - blockDevices:
           # /dev/sdc1   375 GiB
           - blockDeviceName: "blockdevice-eace23032af7703587ec7959d4348c6a"
     poolConfig:
       dataRaidGroupType: "stripe"
