apiVersion: cstor.openebs.io/v1
kind: CStorPoolCluster
metadata:
 name: cstor-disk-pool
 namespace: openebs
spec:
 pools:
   - nodeSelector:
       kubernetes.io/hostname: "gke-kmova-helm-default-pool-7aaf689d-dxf4"
     dataRaidGroups:
       - blockDevices:
           # /dev/sdc1   375 GiB
           - blockDeviceName: "blockdevice-8909a72f4da0f6ba3932ab40bfa833c4"
     poolConfig:
       dataRaidGroupType: "stripe"
 
   - nodeSelector:
       kubernetes.io/hostname: "gke-kmova-helm-default-pool-7aaf689d-phq0"
     dataRaidGroups:
       - blockDevices:
           # /dev/sdc1   375 GiB
           - blockDeviceName: "blockdevice-7066c73e0c79484a60b72e495e713f9f"
     poolConfig:
       dataRaidGroupType: "stripe"
 
   - nodeSelector:
       kubernetes.io/hostname: "gke-kmova-helm-default-pool-7aaf689d-2v8f"
     dataRaidGroups:
       - blockDevices:
           # /dev/sdc1   375 GiB
           - blockDeviceName: "blockdevice-7178e233c399c1b07cc062dfed6bcbce"
     poolConfig:
       dataRaidGroupType: "stripe"
