# Only create this for K8s 1.9+
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-server
provisioner: kubernetes.io/no-provisioner
# Supported policies: Delete, Retain
reclaimPolicy: Delete
