---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openebs-rwx-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "openebs-rwx"
  resources:
    requests:
      storage: 1Gi
