kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fbench-pv-claim
spec:
  storageClassName: managed-nfs-storage
  # storageClassName: gp2
  # storageClassName: local-storage
  # storageClassName: ibmc-block-bronze
  # storageClassName: ibmc-block-silver
  # storageClassName: ibmc-block-gold
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fbench
spec:
  template:
    spec:
      containers:
      - name: fbench
        image: kiranmova/alpine-fio:latest
        imagePullPolicy: Always
        command:
          - sh
          - -c
          - '/docker-entrypoint.sh ext-fio'
        env:
          - name: FBENCH_MOUNTPOINT
            value: /data
          - name: FBENCH_QUICK
            value: "no"
          # - name: FIO_SIZE
          #   value: 1G
          # - name: FIO_OFFSET_INCREMENT
          #   value: 256M
          # - name: FIO_DIRECT
          #   value: "1"
          # - name: RUNTIME
          #   value: "60"
          #
          #   IODEPTH is honoured only if script is triggered
          #   by passing avg-fio as an argument
          # - name: IODEPTH
          #   value: "128"
        volumeMounts:
        - name: fbench-pv
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: fbench-pv
        persistentVolumeClaim:
          claimName: fbench-pv-claim
  backoffLimit: 4
