apiVersion: v1
kind: ResourceQuota
metadata:
  name: openebs-priority
  namespace: openebs
spec:
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - system-node-critical
      - system-cluster-critical
