---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gke-sdb-zpool-init
  labels:
    app: gke-sdb-zpool-init
  annotations:
    command: &cmd apt-get update && apt-get install -y zfsutils-linux && umount -f /dev/sdb && wipefs -af /dev/sdb && zpool create zfspv-pool /dev/sdb
spec:
  selector:
    matchLabels:
      app: gke-sdb-zpool-init
  template:
    metadata:
      labels:
        app: gke-sdb-zpool-init
    spec:
      hostNetwork: true
      initContainers:
      - name: init-node
        command:
          - nsenter
          - --mount=/proc/1/ns/mnt
          - --
          - sh
          - -c
          - *cmd
        image: ubuntu
        securityContext:
          privileged: true
      hostPID: true
      containers:
      - name: wait
        image: k8s.gcr.io/pause:3.1
      hostPID: true
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
  updateStrategy:
    type: RollingUpdate
