---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gke-sdc-partition-init
  labels:
    app: gke-sdc-partition-init
  annotations:
    command: &cmd apt-get update && apt-get install -y parted && umount -f /dev/sdc && wipefs -af /dev/sdc && parted /dev/sdc mklabel gpt && parted /dev/sdc mkpart test-device 1MiB 10MiB
spec:
  selector:
    matchLabels:
      app: gke-sdc-partition-init
  template:
    metadata:
      labels:
        app: gke-sdc-partition-init
    spec:
      hostNetwork: true
      initContainers:
      - name: init-node
        command:
          - nsenter
          - --mount=/proc/1/ns/mnt
          - --
          - sh
          - -c
          - *cmd
        image: ubuntu
        securityContext:
          privileged: true
      hostPID: true
      containers:
      - name: wait
        image: k8s.gcr.io/pause:3.2
      hostPID: true
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
  updateStrategy:
    type: RollingUpdate
