apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: localpv
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: "hostpath"
      - name: BasePath
        value: "/var/openebs/local/"
      #- name: StorageType
      #  value: “hostpath”
      #- name: BasePath
      #  value: “/var/openebs/local/”
provisioner: openebs.io/local
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
#Example for limiting the nodes where hostpath can be provisioned
#allowedTopologies:
#- matchLabelExpressions:
#  - key: kubernetes.io/hostname
#    values:
#    - gke-kmova-helm-default-pool-5d92ea4b-p6qf
